name: Transformer-Classificator
on:
  push:
    branches: [dev, hml, prod]
  pull_request:
    branches: [dev, hml, prod]
jobs:
   ci:
    name: CI - Lint, Format, Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies with uv
      run: |
        run: uv sync --locked --all-extras --dev

    - name: Lint with Ruff
      run: ruff check .
    
    - name: Format with Ruff
      run: ruff format --check .
